### PR TITLE
Upgrades: less exec, and more error handling

### PR DESCRIPTION
**Pull request by gakimball**
The CLI has been in the wild for a week now, and the main thing we've divined as the issues have come in is that the CLI needs better error handling. Here's what this update will change:

- [x] Stop the user if they try to run a command as root (I don't know if people are doing this but it will create problems)
- [x] Add contact and support information to the `help` command
- [x] Before setting up a new project, check if the user has the `git`, `ruby`, and `bundle` commands on their system, and output an error if any are missing
- [x] Check if a folder exists before running `git clone`
- [x] Use npm's programmatic API instead of `exec('npm')`
- [x] Use Bower's programmatic API instead of `exec('bower')`
- [ ] ~~When running `watch`, catch an `EADDRINUSE` error (happens if you try to run a second test server) and output a more friendly error message~~
  - This is a little harder than I thought, because the Gulp exception is being masked by a more generic Node exception. So instead, we might just do that bit of error handling in the `Gulpfile` itself.
- [x] Run `npm install`, `bower install`, and `bundle install` asynchronously
- [x] Catch any errors with the three install steps and alert the user, including instructions on how to get around it (e.g., if the Bundler step fails, just ask the user to run `bundle` themselves)

There's also an issue with users whose systems are configured to require root access to use `npm` and `bundle`. That's sort of a tricky issue to work around, especially with Bundler, because it's a totally external process.

These changes need to be tested in a Windows prompt as well. Using npm and Bower's built-in APIs means two less `exec` commands (it also means the user doesn't need Bower installed on their system), so that cuts down on some cross-platform hassle. We also need to make sure the `which` command properly finds Windows shell commands (apparently it [has issues](https://github.com/isaacs/node-which/issues/9) if you run Bash in Windows, also).

~~It would also be *super nice* if the `new` command could somehow use promises instead of a bunch of nested callbacks, but I don't really know how those work yet ;)~~ Instead I turned a bunch of the tasks and checks into synchronous actions, so I don't need callbacks. And `npm install`, `bower install`, and `bundle` are now run in tandem, instead of one after the other.

### CODE REVIEW

**Comment by gakimball** [comment]
This is about finished, it just needs tested on Windows.

**Comment by AntJanus** [comment]
@gakimball it still fails under `exec-sync`. Not because it's used, but because it's loaded. I checked the stack trace for the error and it goes back to `Module.load`. When I removed it from being required, the module loaded up fine. 

Some other issues:

- It tells me Ruby is not installed, that's because I use JRuby. JRuby is a popular alternative to Ruby for Windows developers because of performance (at least that's what I hear). Easily solved by (ugly) nested try/catch so if `which('ruby')` fails, just do another try/catch inside and do `which('jruby')`. Tested it, works.
- Fails on `Downloading the Foundation for Apps template` with `spawn ENOENT`. Switching to an array representation of the git clone command as: `['git', 'clone', 'https://github.com/zurb/foundation-apps', projectName]` fixed the issue (just copy paste that and replace line 117/118 where `gitClone` is declared.

After that everything seems to work! YAY =D

**Comment by AntJanus** [comment]
Andddd done. Check if this will work on your machine.

**Comment by AntJanus** [comment]
So, Cygwin/Bash on windows works too. I'm adding one more fix (forgot to remove `exec-sync`) so that'll be in the next commit

**Comment by gakimball** [comment]
Hot update: the installer seems to fail if your Node installation requires root access to install things.

Steps to solve it:
  - Figure out how to detect if `npm install` is failing for that reason
  - Spawn a child process as root that re-runs the command
  - Profit

Tomorrow I'll figure out how to SSH into a coworker's machine so I can debug this.

**Pull request merged**
